<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>86bf94e7-074a-419a-9368-d4577feb371b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;userIN&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Email
']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Email
</value>
      <webElementGuid>1d2cc763-a436-4d93-9951-e98698c209ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userIN']</value>
      <webElementGuid>c6bf3218-b85d-467f-9292-1514d8fa80c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_login']/div/div/div[2]/div/div/input</value>
      <webElementGuid>076fdad5-a2e2-4cdf-ad79-fbff831ccdce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>252898d3-06c6-40f6-b428-40f0e2f8329e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'userIN' and @placeholder = 'Enter your email' and @type = 'text']</value>
      <webElementGuid>4131cb44-1548-449a-98a4-88b88024579a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
