<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email</name>
   <tag></tag>
   <elementGuidId>86bf94e7-074a-419a-9368-d4577feb371b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Email
']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#userIN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;userIN&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Email
</value>
      <webElementGuid>7baf7920-0de6-4221-b359-588828878eca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='userIN']</value>
      <webElementGuid>a54ca031-764a-4eb3-bc9c-3441e59f6662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='normal_login']/div/div/div[2]/div/div/input</value>
      <webElementGuid>c5bd5ef1-0b53-4906-a2a9-4a5e22d46245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>75b4c5f2-8a34-4864-8203-56bc21e295fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'userIN' and @placeholder = 'Enter your email' and @type = 'text']</value>
      <webElementGuid>91281cf6-d728-4636-8589-139477e87e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
